#spring.application.name=quizapp
#
## MySQL Database Configuration
##spring.datasource.url=jdbc:mysql://localhost:3306/quizdb
##spring.datasource.username=root
##spring.datasource.password=gaurav
#
## PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://ep-ancient-dawn-aouzx5sl.c-2.ap-southeast-1.aws.neon.tech/quizdb?sslmode=require&channelBinding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_ZK90QoCWGjdB
#
#
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=1
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=240000
#spring.datasource.hikari.keepalive-time=30000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.validation-timeout=5000
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
## Google OAuth2
#
#spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
#spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
#
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#
#
## ================= JWT =================
#
#jwt.secret=YourSecretKeyShouldBeAtLeast32CharactersLong123456
#jwt.expiration=86400000
#
#








spring.application.name=quizapp

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000